### ISSUE TITLE
links im linktree etwas unintuitiv

### ISSUE THREAD

**Issue by Ego-Matthisum** [quiode/dominik-schwaiger.ch#22]
Da sich der "button" um den text verfärbt, dachte ich ursprünglich, dass ich irgendwo im button clicken kann. wäre meiner meinung nach intuiver so, als den link nur im Text zu haben. Ob du das implementierst oder nicht überlasse ich natürlich dir :).

LG

**Comment by quiode** [comment]
stimmt, danke für den tipp :)
